In [1]:
import pandas as pd
import numpy as np

In [2]:
advertisement_df = pd.read_csv("Advertising.csv", index_col = 0)

In [3]:
advertisement_df.head()

,TV,Radio,Newspaper,Sales
1,230.1,37.8,69.2,22.1
2,44.5,39.3,45.1,10.4
3,17.2,45.9,69.3,9.3
4,151.5,41.3,58.5,18.5
5,180.8,10.8,58.4,12.9


In [4]:
X = advertisement_df[["TV"]].to_numpy()
y = advertisement_df[["Sales"]].to_numpy()

## train and test

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
# while passing 2 arrays, we get 4 returned list for both X train, X_Split and Y_train and Y_Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=999)

In [7]:
X_train.shape

(160, 1)

In [8]:
X_test.shape

(40, 1)

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
lin_regression = LinearRegression()

In [13]:
lin_regression.fit(X_train, y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [14]:
# beta_0
lin_regression.intercept_

array([6.83295876])

In [16]:
# beta_1
lin_regression.coef_

array([[0.0483192]])

In [20]:
y_cap = lin_regression.predict(X_train)

In [21]:
y_cap

array([[20.42998256],
       [10.16698379],
       [ 6.8667822 ],
       [19.72935411],
       [18.85477653],
       [ 7.18568895],
       [11.37013195],
       [15.11003828],
       [ 9.71278328],
       [16.16822883],
       [13.32222776],
       [15.76717944],
       [17.38587275],
       [15.38545774],
       [ 9.84324512],
       [10.24429451],
       [18.42473562],
       [ 8.21488798],
       [17.95120743],
       [14.73314849],
       [21.01947684],
       [10.48105861],
       [13.73777291],
       [ 8.04577076],
       [15.38545774],
       [13.66046218],
       [10.0268581 ],
       [10.47139477],
       [12.49596938],
       [16.19238843],
       [14.96991259],
       [14.07117541],
       [12.02244119],
       [11.88714742],
       [11.38462771],
       [ 8.66908849],
       [ 9.24891892],
       [ 7.25333583],
       [19.09637255],
       [17.48734308],
       [18.04784584],
       [19.17368327],
       [19.45876657],
       [12.65542275],
       [ 7.73652786],
       [11

In [24]:
SSE = np.sum(np.power((y_train.flatten() - y_cap.flatten()),2))

In [25]:
SSE

np.float64(1573.6202339696297)

## Evaulation

In [26]:
from sklearn.metrics import max_error, mean_absolute_error, mean_squared_error, r2_score

In [27]:
y_prediction = lin_regression.predict(X_test)

In [28]:
max_error(y_test, y_prediction)

8.402882303051676

In [29]:
mean_absolute_error(y_test, y_prediction)

2.8013040345816433

In [31]:
mean_squared_error(y_test, y_prediction)

13.280971917341802

# R2 coefficient
#### indicates percentage of variance, measure reltioship between your model and dependent variable on a scale of  0 - 100%

In [32]:
r2_score(y_test, y_prediction) 

0.4756277775591903

Description as low percent variance , yo model agadi lagna sakidaina ramro chaina for production 