Creating a NumPy Array:
NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

Task 2:

Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].
Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
Generate an array of 10 evenly spaced values between 0 and 5.

1D

In [68]:
import numpy as np

In [73]:
list_1 = np.array([1,2,3,4,5])

In [74]:
list_1

array([1, 2, 3, 4, 5])

2D

In [54]:
two_d = np.random.randint(1,9 ,size = (3, 3))

In [55]:
two_d

array([[1, 8, 8],
       [4, 6, 5],
       [5, 4, 4]])

In [56]:
evenly_spaced = np.linspace(1, 5, num = 10, axis = 0) #axis define row wise or column wise work, 1 = row, 0 = column

In [57]:
print(np.round(evenly_spaced,3))

[1.    1.444 1.889 2.333 2.778 3.222 3.667 4.111 4.556 5.   ]


Access the element in the second row, third column of the 2D array you created above.

In [58]:
two_d

array([[1, 8, 8],
       [4, 6, 5],
       [5, 4, 4]])

In [59]:
two_d[1:2, 2:]

array([[5]])

Slice the first two rows and the first two columns from the same array.

In [60]:
two_d[:2, :2]

array([[1, 8],
       [4, 6]])

Modify the value in the last row and first column to 100.

In [61]:
two_d[-1, 0] = 100

In [62]:
two_d

array([[  1,   8,   8],
       [  4,   6,   5],
       [100,   4,   4]])

#  Properties and Methods of NumPy Arrays

Find the shape, size, and data type of the 2D array.

In [63]:
two_d.shape

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


(3, 3)

In [64]:
two_d.size

9

In [65]:
type(two_d)

numpy.ndarray

Change the 1D array into a 2D array of shape (5,1).

In [66]:
list_1

[1, 2, 3, 4, 5]

In [77]:
array_1D_2D = np.reshape(list_1,shape = (5,1 ))

In [78]:
array_1D_2D

array([[1],
       [2],
       [3],
       [4],
       [5]])

Flatten a multi-dimensional array back into a 1D array.

In [79]:
array_1D_2D.flatten()

array([1, 2, 3, 4, 5])

# Operations on NumPy Arrays


Add 5 to every element in the 1D array.

In [80]:
list_1

array([1, 2, 3, 4, 5])

In [82]:
addition = np.add(list_1, 5)

In [83]:
addition

array([ 6,  7,  8,  9, 10])

Multiply the 2D array by 3.

In [84]:
two_d

array([[  1,   8,   8],
       [  4,   6,   5],
       [100,   4,   4]])

In [87]:
multiply = np.multiply(two_d, 3)

In [88]:
multiply

array([[  3,  24,  24],
       [ 12,  18,  15],
       [300,  12,  12]])

In [89]:
A = np.array([[1, 2], [3, 4]])

In [90]:
A

array([[1, 2],
       [3, 4]])

In [91]:
B = np.array([[5, 6], [7, 8]])

In [92]:
B

array([[5, 6],
       [7, 8]])

Perform matrix multiplication between the following two arrays:

In [93]:
result = np.dot(A, B)

In [94]:
result

array([[19, 22],
       [43, 50]])

# Understanding Broadcasting

Create a 3x3 matrix of ones and a 1D array of length 3.

In [95]:
three_three = matrix = np.ones((3, 3))

In [96]:
three_three

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [99]:
arrayy= np.array([1, 2, 3])

In [100]:
arrayy

array([1, 2, 3])

Add the 1D array to each row of the matrix using broadcasting.