In [1]:
import numpy as np

In [2]:
a = np.random.randint(10,50, size = (5, 2, 3), dtype = "int16")

In [3]:
a.shape

(5, 2, 3)

In [4]:
a.ndim

3

In [5]:
a.dtype

dtype('int16')

In [6]:
a.size

30

In [8]:
a = np.random.randint(10,50, size = (5, 4), dtype = "int16")

In [10]:
a

array([[21, 43, 47, 27],
       [20, 22, 49, 41],
       [13, 42, 12, 15],
       [42, 46, 20, 12],
       [28, 15, 38, 41]], dtype=int16)

In [11]:
a.reshape(10, 2)

array([[21, 43],
       [47, 27],
       [20, 22],
       [49, 41],
       [13, 42],
       [12, 15],
       [42, 46],
       [20, 12],
       [28, 15],
       [38, 41]], dtype=int16)

In [12]:
a.size

20

In [14]:
b =  a.reshape(2,5,2)

In [15]:
b

array([[[21, 43],
        [47, 27],
        [20, 22],
        [49, 41],
        [13, 42]],

       [[12, 15],
        [42, 46],
        [20, 12],
        [28, 15],
        [38, 41]]], dtype=int16)

In [16]:
a.reshape(5,2, -1) #-1 indicates that it will calculate the matrix size 

array([[[21, 43],
        [47, 27]],

       [[20, 22],
        [49, 41]],

       [[13, 42],
        [12, 15]],

       [[42, 46],
        [20, 12]],

       [[28, 15],
        [38, 41]]], dtype=int16)

In [17]:
a.flatten() #convert any array into linear

array([21, 43, 47, 27, 20, 22, 49, 41, 13, 42, 12, 15, 42, 46, 20, 12, 28,
       15, 38, 41], dtype=int16)

In [19]:
a

array([[21, 43, 47, 27],
       [20, 22, 49, 41],
       [13, 42, 12, 15],
       [42, 46, 20, 12],
       [28, 15, 38, 41]], dtype=int16)

In [20]:
a.sum()

np.int64(594)

In [21]:
a.sum(axis = 0) #column wise, vertical

array([124, 168, 166, 136])

In [22]:
a.sum(axis = 1) #row wise, horizontal

array([138, 132,  82, 120, 122])

In [23]:
a.trace() #sum of diagonals

np.int64(67)

# cumulative sum

In [24]:
a.cumsum()

array([ 21,  64, 111, 138, 158, 180, 229, 270, 283, 325, 337, 352, 394,
       440, 460, 472, 500, 515, 553, 594])

In [25]:
a.cumsum(axis = 1)

array([[ 21,  64, 111, 138],
       [ 20,  42,  91, 132],
       [ 13,  55,  67,  82],
       [ 42,  88, 108, 120],
       [ 28,  43,  81, 122]])

In [28]:
a.prod(dtype = float)

np.float64(3.0205236532848443e+28)

In [29]:
a.prod(axis = 0)

array([ 6420960, 27415080, 21003360,  8169660])

In [30]:
a.cumprod()

array([                  21,                  903,                42441,
                    1145907,             22918140,            504199080,
                24705754920,        1012935951720,       13168167372360,
            553063029639120,     6636756355669440,    99551345335041600,
        4181156504071747200,  7865758450204855040, -8705527659288863744,
        6214132530790944768,  7975014198760488960,  8944748539150024704,
        7859051160929009664,  8626448345027018752])

In [33]:
a

array([[21, 43, 47, 27],
       [20, 22, 49, 41],
       [13, 42, 12, 15],
       [42, 46, 20, 12],
       [28, 15, 38, 41]], dtype=int16)

In [32]:
a.argmax(axis = 0) #maximum value at which index

array([3, 3, 1, 1])

In [35]:
a.flatten()

array([21, 43, 47, 27, 20, 22, 49, 41, 13, 42, 12, 15, 42, 46, 20, 12, 28,
       15, 38, 41], dtype=int16)

In [34]:
a.argmin()

np.int64(10)

In [36]:
a.clip(min = 20, max = 40)

array([[21, 40, 40, 27],
       [20, 22, 40, 40],
       [20, 40, 20, 20],
       [40, 40, 20, 20],
       [28, 20, 38, 40]], dtype=int16)

In [38]:
# concatenation
arr1 = np.random.randint(1, 100, size = (3,3))
arr2 = np.random.randint(1, 100, size = (3,3))

In [39]:
arr1, arr2

(array([[ 9, 19, 54],
        [86, 46, 93],
        [78, 72, 48]]),
 array([[81, 20, 26],
        [85, 63, 69],
        [94,  7, 62]]))

In [42]:
np.concatenate([arr1, arr2], axis = 1) #can use hstack

array([[ 9, 19, 54, 81, 20, 26],
       [86, 46, 93, 85, 63, 69],
       [78, 72, 48, 94,  7, 62]])

In [43]:
np.concatenate([arr1, arr2], axis = 0) #can use vstack

array([[ 9, 19, 54],
       [86, 46, 93],
       [78, 72, 48],
       [81, 20, 26],
       [85, 63, 69],
       [94,  7, 62]])

In [45]:
np.vstack((arr1, arr2))

array([[ 9, 19, 54],
       [86, 46, 93],
       [78, 72, 48],
       [81, 20, 26],
       [85, 63, 69],
       [94,  7, 62]])

In [46]:
np.hstack((arr1, arr2))

array([[ 9, 19, 54, 81, 20, 26],
       [86, 46, 93, 85, 63, 69],
       [78, 72, 48, 94,  7, 62]])