In [1]:
# installing
# !pip install numpy - package for mathematical calculation

In [8]:
import numpy as np

In [3]:
# check version
np.__version__

'2.2.5'

datatype used =  numpy array

In [4]:
# creating numpy array
list1 = [1,2,3,4,5,6,7]
# converting to array
array1 = np.array(list1)

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
# row and column
array1.shape

(7,)

In [8]:
# kati information save gareko cha bhanera dekhaucha - this is linear array
array1.ndim

1

In [9]:
list2 = [[1,2,3], [4,5,6], [7,8,9]]
array2 = np.array(list2)

In [10]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
array2.shape

(3, 3)

In [12]:
# row wise = 1 euta information, column wise = 1 euta information save bhako cha so 2 d
array2.ndim

2

In [13]:
list3 = [
    [
    [1,2,3], [4,5,6], [7,8,9]
    ],[
        [1,2,3], [4,5,6], [7,8,9]

    ]
]
array3 = np.array(list3)

In [14]:
# 2 indicates that  2ta information chaiyeko (row, column)
array3.shape

(2, 3, 3)

In [15]:
array3.ndim

3

Common methods to create numpy arrays

In [16]:
np.zeros(shape = (2, 3, 6), dtype = int)

array([[[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]])

In [17]:
np.ones(shape = (2, 5, 6), dtype = int)

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [19]:
np.full(shape = (2,3), fill_value = 6 )

array([[6, 6, 6],
       [6, 6, 6]])

In [22]:
np.arange(2, 90, 5)

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82,
       87])

In [29]:
np.linspace((0,2), (30, 60), num = 5, axis = 1) #axis define row wise or column wise work, 1 = row, 0 = column

array([[ 0. ,  7.5, 15. , 22.5, 30. ],
       [ 2. , 16.5, 31. , 45.5, 60. ]])

In [30]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [32]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [33]:
np.random.randint(0, 50, size = (2,4))

array([[39,  2,  1, 16],
       [49, 27, 11, 29]])

# Accessing array elements

In [2]:
# indexing and slicing
# 1D
a = np.array([2,3,4,5,6,7])

In [3]:
a

array([2, 3, 4, 5, 6, 7])

In [4]:
a[0]

np.int64(2)

In [5]:
print(a[2::1])

[4 5 6 7]


In [6]:
# reverse
print(a[::-1])

[7 6 5 4 3 2]


In [7]:
# slicing and indexing in 2D
arr1 = np.random.randint(0, 10, size = (5,4))

In [8]:
arr1

array([[7, 6, 1, 8],
       [0, 8, 4, 1],
       [0, 0, 3, 9],
       [3, 6, 7, 4],
       [7, 0, 3, 8]])

In [10]:
arr1[2] #second index ko sabai row dincha

array([0, 0, 3, 9])

In [11]:
arr1[2][-1] #second row ko  index 2 ko last element

np.int64(9)

In [12]:
arr1[-1,-1]

np.int64(8)

In [13]:
# last column access -  slicing 2D array
# array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
arr1[1:4:1, 2:]


array([[4, 1],
       [3, 9],
       [7, 4]])

In [14]:
arr1[::, -2:] #all row last ko 2 ta column

array([[1, 8],
       [4, 1],
       [3, 9],
       [7, 4],
       [3, 8]])

In [15]:
arr1[2:4, 1:3] 

array([[0, 3],
       [6, 7]])

In [2]:
# slicing for N-Dimension
# 3D
np.random.seed(99)
arr2 = np.random.randint(0, 10, size = (3,4,3))

In [3]:
arr2

array([[[1, 3, 9],
        [8, 9, 8],
        [2, 4, 5],
        [4, 1, 7]],

       [[3, 7, 1],
        [1, 0, 6],
        [4, 7, 2],
        [0, 8, 8]],

       [[4, 9, 7],
        [5, 4, 9],
        [1, 9, 0],
        [5, 9, 3]]])

In [4]:
arr2.shape

(3, 4, 3)

In [6]:
# indexing
arr2[1, -1, 0]

np.int64(0)

In [7]:
# slicing
arr2[::, 1, -2:]

array([[9, 8],
       [0, 6],
       [4, 9]])