# Element wise operation

In [1]:
import numpy as np

In [10]:
a = np.array(
    [
        [4,5,6],
        [7,8,9]
    ]
)

b = np.random.randint(1, 45, size = (2,3))

c = np.linspace((0, 5), (60, 100), num = 4, dtype = int)

In [11]:
a, c

(array([[4, 5, 6],
        [7, 8, 9]]),
 array([[  0,   5],
        [ 20,  36],
        [ 40,  68],
        [ 60, 100]]))

# Arithmetic Operation

In [14]:
np.add(a, b)

array([[ 5, 39, 30],
       [33, 26, 38]])

In [15]:
np.subtract(a, b)

array([[  3, -29, -18],
       [-19, -10, -20]])

In [18]:
# power
# a ** 2
np.pow(a, 2) # a ko power raise by 2

array([[16, 25, 36],
       [49, 64, 81]])

In [19]:
# a % b
quo, rem = np.divmod(a,b)
rem

array([[0, 5, 6],
       [7, 8, 9]])

# Trigonometry

In [20]:
np.sin(a)

array([[-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [21]:
cot = np.reciprocal(np.tan(b))

In [22]:
cot

array([[ 0.64209262, -1.60385191, -0.46840674],
       [ 0.84835375, -0.87926488,  1.12721419]])

# round off operation

In [26]:
np.around(cot,2)

array([[ 0.64, -1.6 , -0.47],
       [ 0.85, -0.88,  1.13]])

In [27]:
np.floor(cot)

array([[ 0., -2., -1.],
       [ 0., -1.,  1.]])

In [28]:
np.ceil(cot)

array([[ 1., -1., -0.],
       [ 1., -0.,  2.]])

In [29]:
np.negative(a)

array([[-4, -5, -6],
       [-7, -8, -9]])

# Matrix wise operation

In [30]:
# matrix multiplication

In [40]:
a

array([[4, 5, 6],
       [7, 8, 9]])

In [38]:
# transpose
b_transpose = np.transpose(b)

In [39]:
b_transpose

array([[ 1, 26],
       [34, 18],
       [24, 29]])

In [43]:
# multiplication
result = np.dot(a, b_transpose)
# a.dot(b_transpose)

In [44]:
# trace -  diagnoal sum
d_sum = np.trace(result)
print(d_sum)

905


In [45]:
# rank
np.linalg.matrix_rank(a)

np.int64(2)

In [48]:
# determinant - square matrix ko matra aaucha
c =np.random.randint(1, 5, size = (3,3))

In [50]:
det_b = np.linalg.det(c)

In [51]:
det_b

np.float64(40.000000000000014)

In [55]:
# inverse
inverse_c = np.linalg.inv(c)

In [56]:
print(inverse_c)

[[ 0.25  -0.35   0.2  ]
 [ 0.125  0.225 -0.2  ]
 [-0.25   0.15   0.2  ]]


In [57]:
# solve 4x +2y = 9, 5x + 3y = 9
a = np.array([
    [4, 2],
    [5, 3]
])

In [58]:
a

array([[4, 2],
       [5, 3]])

In [61]:
b = np.array([[8],[9]])

In [62]:
b

array([[8],
       [9]])

In [63]:
a_inverse  = np.linalg.inv(a)

In [64]:
a_inverse

array([[ 1.5, -1. ],
       [-2.5,  2. ]])

In [65]:
np.dot(a_inverse, b)

array([[ 3.],
       [-2.]])

In [ ]:
# Array broadcasting - 